# Nombre del workflow
name: Deploy React App

# Cuándo se debe ejecutar este workflow
on:
  push:
    branches:
      - main # Se ejecuta cada vez que haces push a la rama 'main'

# Los trabajos que se deben realizar
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usar una máquina virtual con Ubuntu

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Usa la misma versión de Node que en tu proyecto

      # Paso 3: Instalar las dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir la aplicación para producción
      - name: Build React app
        run: npm run build

      # Paso 5: Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # La carpeta que se crea con 'npm run build'
